blank_issues_enabled: false
contact_links:
  - name: "ğŸ™ Need help with smooth-scrollbar-deluxe?"
    url: https://github.com/idiotWu/smooth-scrollbar-deluxe/discussions/new?category=q-a
    about: Ask a question in the discussions
